#spring:
#  application:
#    name: msg_backend
#
#  data:
#    mongodb:
#      authentication-database: admin
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
#      database: ${MONGO_DB}
#      port: ${MONGO_PORT}
#      host: ${MONGO_HOST}
#      auto-index-creation: true
#
#  jackson:
#    default-property-inclusion: non_default
